### ISSUE TITLE
No attribute 'EditToolbar'

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [ezequielpereira/Frotz#6]
After porting to python 3 (look at #5  commits) ,  It is giving error in line 
self._edit_toolbar = activity.EditToolbar() in frotz.py -
AttributeError: module 'sugar3.activity.activity' has no attribute 'EditToolbar'.

**Comment by chimosky** [comment]
If you noticed the error while porting to python3, you should try fixing it as there's a possibility your changes introduced the bug.

**Comment by quozl** [comment]
Also, if the error doesn't occur in the _master_ branch, please close this and work the problem on the pull request.  You can find EditToolbar using `git grep` on the Sugar Toolkit repository; if it is not where you think it is.

**Comment by Saumya-Mishra9129** [comment]
Thanks I am closing this issue.
